################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/dummy-canvas-item.c \
../src/eel-canvas-rect.c \
../src/planner-application.c \
../src/planner-assignment-model.c \
../src/planner-calendar-dialog.c \
../src/planner-calendar-selector.c \
../src/planner-calendar.c \
../src/planner-canvas-line.c \
../src/planner-cell-renderer-date.c \
../src/planner-cell-renderer-list.c \
../src/planner-cell-renderer-popup.c \
../src/planner-cmd-manager.c \
../src/planner-column-dialog.c \
../src/planner-conf-gconf.c \
../src/planner-day-type-dialog.c \
../src/planner-default-week-dialog.c \
../src/planner-eds-plugin.c \
../src/planner-format.c \
../src/planner-gantt-background.c \
../src/planner-gantt-chart.c \
../src/planner-gantt-header.c \
../src/planner-gantt-model.c \
../src/planner-gantt-print.c \
../src/planner-gantt-row.c \
../src/planner-gantt-view.c \
../src/planner-group-dialog.c \
../src/planner-group-model.c \
../src/planner-html-plugin.c \
../src/planner-list-model.c \
../src/planner-main.c \
../src/planner-marshal.c \
../src/planner-msp-plugin.c \
../src/planner-pert-chart.c \
../src/planner-pertchartnode.c \
../src/planner-phase-dialog.c \
../src/planner-plugin-loader.c \
../src/planner-plugin.c \
../src/planner-popup-button.c \
../src/planner-popup-entry.c \
../src/planner-predecessor-model.c \
../src/planner-print-dialog.c \
../src/planner-print-job.c \
../src/planner-project-properties.c \
../src/planner-property-dialog.c \
../src/planner-property-model.c \
../src/planner-python-plugin.c \
../src/planner-relation-arrow.c \
../src/planner-resource-cmd.c \
../src/planner-resource-dialog.c \
../src/planner-resource-input-dialog.c \
../src/planner-resource-view.c \
../src/planner-scale-utils.c \
../src/planner-sidebar.c \
../src/planner-simulat.c \
../src/planner-sql-plugin.c \
../src/planner-table-print-sheet.c \
../src/planner-task-cmd.c \
../src/planner-task-date-widget.c \
../src/planner-task-dialog.c \
../src/planner-task-input-dialog.c \
../src/planner-task-popup.c \
../src/planner-task-tree.c \
../src/planner-task-view.c \
../src/planner-usage-chart.c \
../src/planner-usage-model.c \
../src/planner-usage-row.c \
../src/planner-usage-tree.c \
../src/planner-usage-view.c \
../src/planner-util-win32.c \
../src/planner-util.c \
../src/planner-view.c \
../src/planner-window.c \
../src/planner-working-time-dialog.c \
../src/planner-xml-planner-plugin.c 

OBJS += \
./src/dummy-canvas-item.o \
./src/eel-canvas-rect.o \
./src/planner-application.o \
./src/planner-assignment-model.o \
./src/planner-calendar-dialog.o \
./src/planner-calendar-selector.o \
./src/planner-calendar.o \
./src/planner-canvas-line.o \
./src/planner-cell-renderer-date.o \
./src/planner-cell-renderer-list.o \
./src/planner-cell-renderer-popup.o \
./src/planner-cmd-manager.o \
./src/planner-column-dialog.o \
./src/planner-conf-gconf.o \
./src/planner-day-type-dialog.o \
./src/planner-default-week-dialog.o \
./src/planner-eds-plugin.o \
./src/planner-format.o \
./src/planner-gantt-background.o \
./src/planner-gantt-chart.o \
./src/planner-gantt-header.o \
./src/planner-gantt-model.o \
./src/planner-gantt-print.o \
./src/planner-gantt-row.o \
./src/planner-gantt-view.o \
./src/planner-group-dialog.o \
./src/planner-group-model.o \
./src/planner-html-plugin.o \
./src/planner-list-model.o \
./src/planner-main.o \
./src/planner-marshal.o \
./src/planner-msp-plugin.o \
./src/planner-pert-chart.o \
./src/planner-pertchartnode.o \
./src/planner-phase-dialog.o \
./src/planner-plugin-loader.o \
./src/planner-plugin.o \
./src/planner-popup-button.o \
./src/planner-popup-entry.o \
./src/planner-predecessor-model.o \
./src/planner-print-dialog.o \
./src/planner-print-job.o \
./src/planner-project-properties.o \
./src/planner-property-dialog.o \
./src/planner-property-model.o \
./src/planner-python-plugin.o \
./src/planner-relation-arrow.o \
./src/planner-resource-cmd.o \
./src/planner-resource-dialog.o \
./src/planner-resource-input-dialog.o \
./src/planner-resource-view.o \
./src/planner-scale-utils.o \
./src/planner-sidebar.o \
./src/planner-simulat.o \
./src/planner-sql-plugin.o \
./src/planner-table-print-sheet.o \
./src/planner-task-cmd.o \
./src/planner-task-date-widget.o \
./src/planner-task-dialog.o \
./src/planner-task-input-dialog.o \
./src/planner-task-popup.o \
./src/planner-task-tree.o \
./src/planner-task-view.o \
./src/planner-usage-chart.o \
./src/planner-usage-model.o \
./src/planner-usage-row.o \
./src/planner-usage-tree.o \
./src/planner-usage-view.o \
./src/planner-util-win32.o \
./src/planner-util.o \
./src/planner-view.o \
./src/planner-window.o \
./src/planner-working-time-dialog.o \
./src/planner-xml-planner-plugin.o 

C_DEPS += \
./src/dummy-canvas-item.d \
./src/eel-canvas-rect.d \
./src/planner-application.d \
./src/planner-assignment-model.d \
./src/planner-calendar-dialog.d \
./src/planner-calendar-selector.d \
./src/planner-calendar.d \
./src/planner-canvas-line.d \
./src/planner-cell-renderer-date.d \
./src/planner-cell-renderer-list.d \
./src/planner-cell-renderer-popup.d \
./src/planner-cmd-manager.d \
./src/planner-column-dialog.d \
./src/planner-conf-gconf.d \
./src/planner-day-type-dialog.d \
./src/planner-default-week-dialog.d \
./src/planner-eds-plugin.d \
./src/planner-format.d \
./src/planner-gantt-background.d \
./src/planner-gantt-chart.d \
./src/planner-gantt-header.d \
./src/planner-gantt-model.d \
./src/planner-gantt-print.d \
./src/planner-gantt-row.d \
./src/planner-gantt-view.d \
./src/planner-group-dialog.d \
./src/planner-group-model.d \
./src/planner-html-plugin.d \
./src/planner-list-model.d \
./src/planner-main.d \
./src/planner-marshal.d \
./src/planner-msp-plugin.d \
./src/planner-pert-chart.d \
./src/planner-pertchartnode.d \
./src/planner-phase-dialog.d \
./src/planner-plugin-loader.d \
./src/planner-plugin.d \
./src/planner-popup-button.d \
./src/planner-popup-entry.d \
./src/planner-predecessor-model.d \
./src/planner-print-dialog.d \
./src/planner-print-job.d \
./src/planner-project-properties.d \
./src/planner-property-dialog.d \
./src/planner-property-model.d \
./src/planner-python-plugin.d \
./src/planner-relation-arrow.d \
./src/planner-resource-cmd.d \
./src/planner-resource-dialog.d \
./src/planner-resource-input-dialog.d \
./src/planner-resource-view.d \
./src/planner-scale-utils.d \
./src/planner-sidebar.d \
./src/planner-simulat.d \
./src/planner-sql-plugin.d \
./src/planner-table-print-sheet.d \
./src/planner-task-cmd.d \
./src/planner-task-date-widget.d \
./src/planner-task-dialog.d \
./src/planner-task-input-dialog.d \
./src/planner-task-popup.d \
./src/planner-task-tree.d \
./src/planner-task-view.d \
./src/planner-usage-chart.d \
./src/planner-usage-model.d \
./src/planner-usage-row.d \
./src/planner-usage-tree.d \
./src/planner-usage-view.d \
./src/planner-util-win32.d \
./src/planner-util.d \
./src/planner-view.d \
./src/planner-window.d \
./src/planner-working-time-dialog.d \
./src/planner-xml-planner-plugin.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I/usr/include/gtk-2.0 -I/usr/lib/i386-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/lib/gtk-2.0/include -I/usr/include/libgnomeui-2.0 -I/usr/include/gnome-vfs-2.0 -I/usr/include/libxml2 -I/usr/include -I/usr/include/gtk-unix-print-2.0 -I/usr/include/libglade-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/glib-2.0 -O0 -g3 -Wall -c -fmessage-length=0 `pkg-config --cflags gtk+-2.0` -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


